services:
  api:
    container_name: api
    restart: always
    ports:
      - 7006:8080
    build:
      context: ./Backend/src/
      dockerfile: ./WebApi/Dockerfile
    environment:
      TZ: America/Sao_Paulo
  frontend:
    restart: always
    build:
      context: ./Frontend
    ports:
      - "3039:80"
    environment:
      - NODE_ENV=production
volumes:
  sql-storage: